### PR TITLE
Upgrade to lilypond 2.22

### PR DESCRIPTION
**Pull request by bjgbeelen**
I've been using your docker image from dockerhub quite a lot lately. I just noticed there is a new release of Lilypond, and i would like to keep using the 'latest' version.

I don't think merging this will automatically deploy it to Dockerhub or did i miss something?

### CODE REVIEW

**Review by iskaron — APPROVED** [review]

**Comment by iskaron** [comment]
Oh, great, thanks for your PR :) Haven't had time to update this project.
And you are right, apparently I did not setup automatic build for this github project, but I will at least build it manually :)

**Comment by iskaron** [comment]
Hm. I did set it up. No idea, why the trigger wasn't firing on dockerhub. I triggered it manually, should be finished in a moment or so.

**Comment by iskaron** [comment]
Aaaaand done. iskaron/lilypond:latest is now 2.22. Again, thanks :)

**Comment by bjgbeelen** [comment]
Sweet! Thanks for the swift response!

**Pull request merged**
